config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :room_messages
  resources :rooms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

  def as_json(options)
    super(options).merge(
      username: user.username, user_avatar_url: user.gravatar_url
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable
  validates :username, uniqueness: true, presence: true

  def gravatar_url
    gravatar_id = Digest::MD5.hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username])
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_entities

  def create
    @room_message =
      RoomMessage.create(
        user: current_user,
        room: @room,
        message: params.dig(:room_message, :message)
      )
    RoomChannel.broadcast_to @room, @room_message
    head :ok
  end

  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :load_room, only: %i[show edit update]
  before_action :load_rooms, only: %i[show]

  def index
    @rooms = Room.all
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:success] = "Room #{@room.name} created successfully"
      redirect_to rooms_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @room.update_attributes(room_params)
      flash[:success] = "Room #{@room.name} updated successfully"
    else
      render 'edit'
    end
  end

  protected

  def load_room
    @room = Room.find(params[:id]) if params[:id]
  end

  def load_rooms
    @rooms = Room.all
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper; end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsChatTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-gray-800 bg-gray-600">
    <%= render 'shared/navigation' %>
    <div class="md:w-10/12 mt-2 mx-auto">
      <%= yield %>
    </div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_for @room do |f| %>
  <div class="field mb-6">
    <%= f.label :name, class: 'block text-gray-700 mb-1 font-bold' %>
    <%= f.text_field :name, class: 'shadow appearance-none rounded w-full border px-3 py-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
  </div>
  <%= f.submit 'Save', role: 'button', class: 'shadow bg-teal-700 hover:bg-teal-900 hover:shadow-xl focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded' %>
<% end %>

app/views/rooms/_rooms.html.erb
<%= link_to 'Create room', new_room_path, class: 'block m-1 p-2 text-white rounded bg-teal-700 hover:bg-teal-900 hover:shadow-xl' %>
<% if @rooms.present? %>
<div class="bg-blue-100 border-aqua p-2">
  <% @rooms.each do |room| %>
  <div class="truncate
  ">
    <%= link_to room.name, room_path(room), class: 'inline-block bg-teal-600 hover:bg-teal-800 text-white mt-4 rounded px-2 py-1' %>
  </div>
  <% end %>
</div>
<% else %>
  <p>There are no rooms available.</p>
<% end%>

app/views/rooms/edit.html.erb
<div class="px-4 md:w-3/4 mx-auto py-4 m-1 rounded-lg shadow-md bg-white">
  <h1 class="text-center text-2xl text-gray-600 font-bold m-2">Edit Room <%= @room.name %></h1>
  <%= render 'form' %>
  </div>

app/views/rooms/index.html.erb
<div class="flex">
  <div class="w-1/4 px-2 py-2 m-1 rounded-lg shadow-md bg-white">
    <%= render 'rooms' %>
  </div>
  
  <div class="w-3/4 px-4 py-2 m-1 rounded-lg shadow-md bg-white">
    <div class="bg-teal-100 h-full text-teal-900 border-lg rounded p-2">
      <h1 class="text-2xl text-gray-600 font-bold">Welcome to Rails Chat Tutorial</h1>
      <p class="text-teal-500">We need to talk</p>
      <hr />
      <p class="text-teal-400">You can join a room or create a new room from the sidebar</p>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="px-4 md:w-3/4 mx-auto py-4 m-1 rounded-lg shadow-md bg-white">
  <h1 class="text-center text-2xl text-gray-600 font-bold  m-2">Create Room</h1>
  <%= render 'form' %>
  </div>

app/views/rooms/show.html.erb
<div class="flex">
  <div class="w-1/4 px-2 py-2 m-1 rounded-lg shadow-md bg-white">
    <%= render 'rooms' %>
  </div>
  
  <div class="flex flex-col w-3/4">

    <div class=" px-4 py-2 m-1 rounded-lg shadow-md bg-white">

      <div class="bg-teal-100 overflow-hidden overflow-y-scroll relative h-full w-full text-teal-900 border-lg rounded p-2">
        <h1 class="text-2xl text-center text-gray-800 font-bold"><%= @room.name %></h1>
        <hr />

        <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
          <% @room_messages.each do |room_message| %>

            <div data-role="message-template" class="flex items-center m-2">
              <div class="p-3 rounded-full bg-teal-200">
                <img src="<%= room_message.user.gravatar_url %>" class="h-8 w-8 rounded-full object-cover object-fit" alt="Profile" />
              </div>     
              <div class="ml-1 w-full p-2 rounded-lg bg-teal-200 text-gray-900">
              <div class="text-sm text-right">
                  <small class="uppercase leading-tight text-gray-600" data-role="message-date"><%= room_message.user.username %></small>
                </div>
                <div data-role="message-text" class="text-base text-gray-800"><%= room_message.message %></div>
                <div class="text-sm text-right">
                  <small class="leading-tight text-gray-600" data-role="message-date"><%= time_ago_in_words(room_message.created_at) %></small>
                </div>
              </div>
            </div>

          <% end %>
        </div>
        <hr />
      </div>
    </div>
    <div class="px-4 py-2 m-1 rounded-lg shadow-md bg-white">
      <%= form_for @room_message, remote: true, data: { controller: 'room-message', action: 'ajax:success->room-message#onPostSuccess' }, html: {class: 'w-full'} do |f| %>
      <div class="flex mb-1 w-full">
          <%= f.text_field :message, autofocus: true, data: { target: 'room-message.message' }, class: 'w-full shadow appearance-none rounded border px-3 py-3 text-white  focus:outline-none focus:shadow-outline bg-gray-700 font-bold', placeholder: 'type you message....' %>
          <%= f.submit 'Send', class: 'shadow bg-teal-700 ml-auto hover:bg-teal-900 hover:shadow-xl focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded' %>
          <%= f.hidden_field :room_id, as: :hidden %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navigation.html.erb
<header class="bg-gray-800 text-white p-2">
  <div class="flex mx-auto justify-between items-center w-10/12">
    <div>
      <%= link_to 'Rails chat tutorial', root_url, class: 'font-bold text-gray-500 hover:text-white text-xl tracking-tight'%>
    </div>

    <div>
    <% if current_user %>
        <div class="flex justify-between items-center">
          <button class="flex items-center text-white text-xl hover:font-bold" role="button">
            <img src="<%= current_user.gravatar_url %>" class="h-8 rounded-full"> 
            <span class="ml-2"><%= current_user.username %></span>
          </button>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'inline-block bg-teal-700 hover:bg-teal-800 rounded-full px-4 py-2 ml-8 font-bold'  %>
        </div>
    <% end %>
    </div>

  </div>
</header>